# Generated by Django 5.0 on 2023-12-24 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Запись в блоге', 'verbose_name_plural': 'Запись в блоге'},
        ),
    ]
